<?php

use Illuminate\Database\Seeder;

class CurrencyTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('currency')->delete();
        
        \DB::table('currency')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'United Arab Emirates Dirham',
                'alphacode' => 'AED',
                'api_code' => 'USDAED',
                'api_code_eur' => 'EURAED',
                'rates' => 3.672699,
                'rates_eur' => 4.304624,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:10:58',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Afghan Afghani',
                'alphacode' => 'AFN',
                'api_code' => 'USDAFN',
                'api_code_eur' => 'EURAFN',
                'rates' => 71.349998,
                'rates_eur' => 84.622699,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:10:58',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Albanian Lek',
                'alphacode' => 'ALL',
                'api_code' => 'USDALL',
                'api_code_eur' => 'EURALL',
                'rates' => 108.489998,
                'rates_eur' => 126.25426,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:10:58',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Armenian Dram',
                'alphacode' => 'AMD',
                'api_code' => 'USDAMD',
                'api_code_eur' => 'EURAMD',
                'rates' => 482.089996,
                'rates_eur' => 564.745188,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:10:58',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Netherlands Antillean Guilder',
                'alphacode' => 'ANG',
                'api_code' => 'USDANG',
                'api_code_eur' => 'EURANG',
                'rates' => 1.812499,
                'rates_eur' => 2.121937,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:10:58',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Angolan Kwanza',
                'alphacode' => 'AOA',
                'api_code' => 'USDAOA',
                'api_code_eur' => 'EURAOA',
                'rates' => 245.468002,
                'rates_eur' => 285.806738,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:10:59',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Argentine Peso',
                'alphacode' => 'ARS',
                'api_code' => 'USDARS',
                'api_code_eur' => 'EURARS',
                'rates' => 27.573005,
                'rates_eur' => 31.739644,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:10:59',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Australian Dollar',
                'alphacode' => 'AUD',
                'api_code' => 'USDAUD',
                'api_code_eur' => 'EURAUD',
                'rates' => 1.3488,
                'rates_eur' => 1.58099,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:10:59',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Aruban Florin',
                'alphacode' => 'AWG',
                'api_code' => 'USDAWG',
                'api_code_eur' => 'EURAWG',
                'rates' => 1.78,
                'rates_eur' => 2.086266,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:10:59',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Azerbaijani Manat',
                'alphacode' => 'AZN',
                'api_code' => 'USDAZN',
                'api_code_eur' => 'EURAZN',
                'rates' => 1.699496,
                'rates_eur' => 1.991913,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:10:59',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Bosnia-Herzegovina Convertible Mark',
                'alphacode' => 'BAM',
                'api_code' => 'USDBAM',
                'api_code_eur' => 'EURBAM',
                'rates' => 1.683503,
                'rates_eur' => 1.959095,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:10:59',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Barbadian Dollar',
                'alphacode' => 'BBD',
                'api_code' => 'USDBBD',
                'api_code_eur' => 'EURBBD',
                'rates' => 2.0,
                'rates_eur' => 2.344119,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:10:59',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Bangladeshi Taka',
                'alphacode' => 'BDT',
                'api_code' => 'USDBDT',
                'api_code_eur' => 'EURBDT',
                'rates' => 83.989998,
                'rates_eur' => 98.441283,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:10:59',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Bulgarian Lev',
                'alphacode' => 'BGN',
                'api_code' => 'USDBGN',
                'api_code_eur' => 'EURBGN',
                'rates' => 1.684196,
                'rates_eur' => 1.959331,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:10:59',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Bahraini Dinar',
                'alphacode' => 'BHD',
                'api_code' => 'USDBHD',
                'api_code_eur' => 'EURBHD',
                'rates' => 0.377704,
                'rates_eur' => 0.445506,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:10:59',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Burundian Franc',
                'alphacode' => 'BIF',
                'api_code' => 'USDBIF',
                'api_code_eur' => 'EURBIF',
                'rates' => 1750.97998,
                'rates_eur' => 2052.252877,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:10:59',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Bermudan Dollar',
                'alphacode' => 'BMD',
                'api_code' => 'USDBMD',
                'api_code_eur' => 'EURBMD',
                'rates' => 1.0,
                'rates_eur' => 1.17206,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:10:59',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Brunei Dollar',
                'alphacode' => 'BND',
                'api_code' => 'USDBND',
                'api_code_eur' => 'EURBND',
                'rates' => 1.337799,
                'rates_eur' => 1.575949,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:10:59',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Bolivian Boliviano',
                'alphacode' => 'BOB',
                'api_code' => 'USDBOB',
                'api_code_eur' => 'EURBOB',
                'rates' => 6.860211,
                'rates_eur' => 8.040757,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:10:59',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Brazilian Real',
                'alphacode' => 'BRL',
                'api_code' => 'USDBRL',
                'api_code_eur' => 'EURBRL',
                'rates' => 3.749494,
                'rates_eur' => 4.424871,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:10:59',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Bahamian Dollar',
                'alphacode' => 'BSD',
                'api_code' => 'USDBSD',
                'api_code_eur' => 'EURBSD',
                'rates' => 1.0,
                'rates_eur' => 1.17206,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:10:59',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Bitcoin',
                'alphacode' => 'BTC',
                'api_code' => 'USDBTC',
                'api_code_eur' => 'EURBTC',
                'rates' => 0.000149,
                'rates_eur' => 0.000188,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:10:59',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Bhutanese Ngultrum',
                'alphacode' => 'BTN',
                'api_code' => 'USDBTN',
                'api_code_eur' => 'EURBTN',
                'rates' => 67.949997,
                'rates_eur' => 79.465644,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:10:59',
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Botswanan Pula',
                'alphacode' => 'BWP',
                'api_code' => 'USDBWP',
                'api_code_eur' => 'EURBWP',
                'rates' => 10.283102,
                'rates_eur' => 12.102216,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:10:59',
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'Belarusian Ruble',
                'alphacode' => 'BYR',
                'api_code' => 'USDBYR',
                'api_code_eur' => 'EURBYR',
                'rates' => 19600.0,
                'rates_eur' => 22972.367959,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:10:59',
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'Belize Dollar',
                'alphacode' => 'BZD',
                'api_code' => 'USDBZD',
                'api_code_eur' => 'EURBZD',
                'rates' => 1.997798,
                'rates_eur' => 2.341537,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:00',
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'Canadian Dollar',
                'alphacode' => 'CAD',
                'api_code' => 'USDCAD',
                'api_code_eur' => 'EURCAD',
                'rates' => 1.32082,
                'rates_eur' => 1.557866,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:00',
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'Congolese Franc',
                'alphacode' => 'CDF',
                'api_code' => 'USDCDF',
                'api_code_eur' => 'EURCDF',
                'rates' => 1565.523681,
                'rates_eur' => 1834.862388,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:00',
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'Swiss Franc',
                'alphacode' => 'CHF',
                'api_code' => 'USDCHF',
                'api_code_eur' => 'EURCHF',
                'rates' => 0.99324,
                'rates_eur' => 1.155628,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:00',
            ),
            29 => 
            array (
                'id' => 30,
            'name' => 'Chilean Unit of Account (UF)',
                'alphacode' => 'CLF',
                'api_code' => 'USDCLF',
                'api_code_eur' => 'EURCLF',
                'rates' => 0.02322,
                'rates_eur' => 0.027286,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:00',
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'Chilean Peso',
                'alphacode' => 'CLP',
                'api_code' => 'USDCLP',
                'api_code_eur' => 'EURCLP',
                'rates' => 636.599976,
                'rates_eur' => 748.37178,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:00',
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'Chinese Yuan',
                'alphacode' => 'CNY',
                'api_code' => 'USDCNY',
                'api_code_eur' => 'EURCNY',
                'rates' => 6.437806,
                'rates_eur' => 7.68179,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:00',
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'Colombian Peso',
                'alphacode' => 'COP',
                'api_code' => 'USDCOP',
                'api_code_eur' => 'EURCOP',
                'rates' => 2922.100098,
                'rates_eur' => 3417.491409,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:00',
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'Costa Rican Colón',
                'alphacode' => 'CRC',
                'api_code' => 'USDCRC',
                'api_code_eur' => 'EURCRC',
                'rates' => 564.450012,
                'rates_eur' => 661.920988,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:00',
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'Cuban Convertible Peso',
                'alphacode' => 'CUC',
                'api_code' => 'USDCUC',
                'api_code_eur' => 'EURCUC',
                'rates' => 1.0,
                'rates_eur' => 1.17206,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:00',
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'Cuban Peso',
                'alphacode' => 'CUP',
                'api_code' => 'USDCUP',
                'api_code_eur' => 'EURCUP',
                'rates' => 26.5,
                'rates_eur' => 31.059579,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:00',
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'Cape Verdean Escudo',
                'alphacode' => 'CVE',
                'api_code' => 'USDCVE',
                'api_code_eur' => 'EURCVE',
                'rates' => 94.800003,
                'rates_eur' => 110.302529,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:00',
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'Czech Republic Koruna',
                'alphacode' => 'CZK',
                'api_code' => 'USDCZK',
                'api_code_eur' => 'EURCZK',
                'rates' => 22.15599,
                'rates_eur' => 25.88869,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:00',
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'Djiboutian Franc',
                'alphacode' => 'DJF',
                'api_code' => 'USDDJF',
                'api_code_eur' => 'EURDJF',
                'rates' => 177.441813,
                'rates_eur' => 208.053133,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:00',
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'Danish Krone',
                'alphacode' => 'DKK',
                'api_code' => 'USDDKK',
                'api_code_eur' => 'EURDKK',
                'rates' => 6.40548,
                'rates_eur' => 7.454346,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:00',
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'Dominican Peso',
                'alphacode' => 'DOP',
                'api_code' => 'USDDOP',
                'api_code_eur' => 'EURDOP',
                'rates' => 49.549999,
                'rates_eur' => 58.087274,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:00',
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'Algerian Dinar',
                'alphacode' => 'DZD',
                'api_code' => 'USDDZD',
                'api_code_eur' => 'EURDZD',
                'rates' => 117.009003,
                'rates_eur' => 136.993845,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:00',
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'Egyptian Pound',
                'alphacode' => 'EGP',
                'api_code' => 'USDEGP',
                'api_code_eur' => 'EUREGP',
                'rates' => 17.799999,
                'rates_eur' => 20.909718,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:00',
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'Eritrean Nakfa',
                'alphacode' => 'ERN',
                'api_code' => 'USDERN',
                'api_code_eur' => 'EURERN',
                'rates' => 14.989537,
                'rates_eur' => 17.569202,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:00',
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'Ethiopian Birr',
                'alphacode' => 'ETB',
                'api_code' => 'USDETB',
                'api_code_eur' => 'EURETB',
                'rates' => 27.230068,
                'rates_eur' => 31.903461,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:01',
            ),
            45 => 
            array (
                'id' => 46,
                'name' => 'Euro',
                'alphacode' => 'EUR',
                'api_code' => 'USDEUR',
                'api_code_eur' => 'EUREUR',
                'rates' => 0.859299,
                'rates_eur' => 1.0,
                'created_at' => NULL,
                'updated_at' => '2018-06-19 01:18:57',
            ),
            46 => 
            array (
                'id' => 47,
                'name' => 'Fijian Dollar',
                'alphacode' => 'FJD',
                'api_code' => 'USDFJD',
                'api_code_eur' => 'EURFJD',
                'rates' => 2.074997,
                'rates_eur' => 2.430851,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:01',
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'Falkland Islands Pound',
                'alphacode' => 'FKP',
                'api_code' => 'USDFKP',
                'api_code_eur' => 'EURFKP',
                'rates' => 0.754698,
                'rates_eur' => 0.882211,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:01',
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'British Pound Sterling',
                'alphacode' => 'GBP',
                'api_code' => 'USDGBP',
                'api_code_eur' => 'EURGBP',
                'rates' => 0.753903,
                'rates_eur' => 0.882046,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:01',
            ),
            49 => 
            array (
                'id' => 50,
                'name' => 'Georgian Lari',
                'alphacode' => 'GEL',
                'api_code' => 'USDGEL',
                'api_code_eur' => 'EURGEL',
                'rates' => 2.448601,
                'rates_eur' => 2.863459,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:01',
            ),
            50 => 
            array (
                'id' => 51,
                'name' => 'Guernsey Pound',
                'alphacode' => 'GGP',
                'api_code' => 'USDGGP',
                'api_code_eur' => 'EURGGP',
                'rates' => 0.753992,
                'rates_eur' => 0.882001,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:01',
            ),
            51 => 
            array (
                'id' => 52,
                'name' => 'Ghanaian Cedi',
                'alphacode' => 'GHS',
                'api_code' => 'USDGHS',
                'api_code_eur' => 'EURGHS',
                'rates' => 4.698499,
                'rates_eur' => 5.562635,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:01',
            ),
            52 => 
            array (
                'id' => 53,
                'name' => 'Gibraltar Pound',
                'alphacode' => 'GIP',
                'api_code' => 'USDGIP',
                'api_code_eur' => 'EURGIP',
                'rates' => 0.755006,
                'rates_eur' => 0.882445,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:01',
            ),
            53 => 
            array (
                'id' => 54,
                'name' => 'Gambian Dalasi',
                'alphacode' => 'GMD',
                'api_code' => 'USDGMD',
                'api_code_eur' => 'EURGMD',
                'rates' => 46.849998,
                'rates_eur' => 54.794098,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:01',
            ),
            54 => 
            array (
                'id' => 55,
                'name' => 'Guinean Franc',
                'alphacode' => 'GNF',
                'api_code' => 'USDGNF',
                'api_code_eur' => 'EURGNF',
                'rates' => 9002.000197,
                'rates_eur' => 10552.052029,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:01',
            ),
            55 => 
            array (
                'id' => 56,
                'name' => 'Guatemalan Quetzal',
                'alphacode' => 'GTQ',
                'api_code' => 'USDGTQ',
                'api_code_eur' => 'EURGTQ',
                'rates' => 7.481997,
                'rates_eur' => 8.77757,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:01',
            ),
            56 => 
            array (
                'id' => 57,
                'name' => 'Guyanaese Dollar',
                'alphacode' => 'GYD',
                'api_code' => 'USDGYD',
                'api_code_eur' => 'EURGYD',
                'rates' => 206.089996,
                'rates_eur' => 241.772451,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:01',
            ),
            57 => 
            array (
                'id' => 58,
                'name' => 'Hong Kong Dollar',
                'alphacode' => 'HKD',
                'api_code' => 'USDHKD',
                'api_code_eur' => 'EURHKD',
                'rates' => 7.8493,
                'rates_eur' => 9.197739,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:01',
            ),
            58 => 
            array (
                'id' => 59,
                'name' => 'Honduran Lempira',
                'alphacode' => 'HNL',
                'api_code' => 'USDHNL',
                'api_code_eur' => 'EURHNL',
                'rates' => 23.888023,
                'rates_eur' => 28.018086,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:01',
            ),
            59 => 
            array (
                'id' => 60,
                'name' => 'Croatian Kuna',
                'alphacode' => 'HRK',
                'api_code' => 'USDHRK',
                'api_code_eur' => 'EURHRK',
                'rates' => 6.338299,
                'rates_eur' => 7.411634,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:01',
            ),
            60 => 
            array (
                'id' => 61,
                'name' => 'Haitian Gourde',
                'alphacode' => 'HTG',
                'api_code' => 'USDHTG',
                'api_code_eur' => 'EURHTG',
                'rates' => 66.120003,
                'rates_eur' => 77.848196,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:01',
            ),
            61 => 
            array (
                'id' => 62,
                'name' => 'Hungarian Forint',
                'alphacode' => 'HUF',
                'api_code' => 'USDHUF',
                'api_code_eur' => 'EURHUF',
                'rates' => 278.279999,
                'rates_eur' => 325.50439,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:01',
            ),
            62 => 
            array (
                'id' => 63,
                'name' => 'Indonesian Rupiah',
                'alphacode' => 'IDR',
                'api_code' => 'USDIDR',
                'api_code_eur' => 'EURIDR',
                'rates' => 13925.0,
                'rates_eur' => 16613.944685,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:01',
            ),
            63 => 
            array (
                'id' => 64,
                'name' => 'Israeli New Sheqel',
                'alphacode' => 'ILS',
                'api_code' => 'USDILS',
                'api_code_eur' => 'EURILS',
                'rates' => 3.636698,
                'rates_eur' => 4.23665,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:02',
            ),
            64 => 
            array (
                'id' => 65,
                'name' => 'Manx pound',
                'alphacode' => 'IMP',
                'api_code' => 'USDIMP',
                'api_code_eur' => 'EURIMP',
                'rates' => 0.753992,
                'rates_eur' => 0.882001,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:02',
            ),
            65 => 
            array (
                'id' => 66,
                'name' => 'Indian Rupee',
                'alphacode' => 'INR',
                'api_code' => 'USDINR',
                'api_code_eur' => 'EURINR',
                'rates' => 68.029999,
                'rates_eur' => 79.845969,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:02',
            ),
            66 => 
            array (
                'id' => 67,
                'name' => 'Iraqi Dinar',
                'alphacode' => 'IQD',
                'api_code' => 'USDIQD',
                'api_code_eur' => 'EURIQD',
                'rates' => 1184.0,
                'rates_eur' => 1387.718554,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:02',
            ),
            67 => 
            array (
                'id' => 68,
                'name' => 'Iranian Rial',
                'alphacode' => 'IRR',
                'api_code' => 'USDIRR',
                'api_code_eur' => 'EURIRR',
                'rates' => 42419.999861,
                'rates_eur' => 49835.973901,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:02',
            ),
            68 => 
            array (
                'id' => 69,
                'name' => 'Icelandic Króna',
                'alphacode' => 'ISK',
                'api_code' => 'USDISK',
                'api_code_eur' => 'EURISK',
                'rates' => 108.750455,
                'rates_eur' => 126.230814,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:02',
            ),
            69 => 
            array (
                'id' => 70,
                'name' => 'Jersey Pound',
                'alphacode' => 'JEP',
                'api_code' => 'USDJEP',
                'api_code_eur' => 'EURJEP',
                'rates' => 0.753992,
                'rates_eur' => 0.882001,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:02',
            ),
            70 => 
            array (
                'id' => 71,
                'name' => 'Jamaican Dollar',
                'alphacode' => 'JMD',
                'api_code' => 'USDJMD',
                'api_code_eur' => 'EURJMD',
                'rates' => 130.559998,
                'rates_eur' => 152.297425,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:02',
            ),
            71 => 
            array (
                'id' => 72,
                'name' => 'Jordanian Dinar',
                'alphacode' => 'JOD',
                'api_code' => 'USDJOD',
                'api_code_eur' => 'EURJOD',
                'rates' => 0.708503,
                'rates_eur' => 0.830408,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:02',
            ),
            72 => 
            array (
                'id' => 73,
                'name' => 'Japanese Yen',
                'alphacode' => 'JPY',
                'api_code' => 'USDJPY',
                'api_code_eur' => 'EURJPY',
                'rates' => 110.128998,
                'rates_eur' => 128.285442,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:02',
            ),
            73 => 
            array (
                'id' => 74,
                'name' => 'Kenyan Shilling',
                'alphacode' => 'KES',
                'api_code' => 'USDKES',
                'api_code_eur' => 'EURKES',
                'rates' => 100.849998,
                'rates_eur' => 117.850595,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:02',
            ),
            74 => 
            array (
                'id' => 75,
                'name' => 'Kyrgystani Som',
                'alphacode' => 'KGS',
                'api_code' => 'USDKGS',
                'api_code_eur' => 'EURKGS',
                'rates' => 68.281799,
                'rates_eur' => 79.857112,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:02',
            ),
            75 => 
            array (
                'id' => 76,
                'name' => 'Cambodian Riel',
                'alphacode' => 'KHR',
                'api_code' => 'USDKHR',
                'api_code_eur' => 'EURKHR',
                'rates' => 4029.800049,
                'rates_eur' => 4691.285829,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:02',
            ),
            76 => 
            array (
                'id' => 77,
                'name' => 'Comorian Franc',
                'alphacode' => 'KMF',
                'api_code' => 'USDKMF',
                'api_code_eur' => 'EURKMF',
                'rates' => 421.999563,
                'rates_eur' => 494.257543,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:02',
            ),
            77 => 
            array (
                'id' => 78,
                'name' => 'North Korean Won',
                'alphacode' => 'KPW',
                'api_code' => 'USDKPW',
                'api_code_eur' => 'EURKPW',
                'rates' => 899.999935,
                'rates_eur' => 1054.853397,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:02',
            ),
            78 => 
            array (
                'id' => 79,
                'name' => 'South Korean Won',
                'alphacode' => 'KRW',
                'api_code' => 'USDKRW',
                'api_code_eur' => 'EURKRW',
                'rates' => 1105.512855,
                'rates_eur' => 1307.54965,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:02',
            ),
            79 => 
            array (
                'id' => 80,
                'name' => 'Kuwaiti Dinar',
                'alphacode' => 'KWD',
                'api_code' => 'USDKWD',
                'api_code_eur' => 'EURKWD',
                'rates' => 0.302401,
                'rates_eur' => 0.354194,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:02',
            ),
            80 => 
            array (
                'id' => 81,
                'name' => 'Cayman Islands Dollar',
                'alphacode' => 'KYD',
                'api_code' => 'USDKYD',
                'api_code_eur' => 'EURKYD',
                'rates' => 0.819756,
                'rates_eur' => 0.961049,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:02',
            ),
            81 => 
            array (
                'id' => 82,
                'name' => 'Kazakhstani Tenge',
                'alphacode' => 'KZT',
                'api_code' => 'USDKZT',
                'api_code_eur' => 'EURKZT',
                'rates' => 339.660004,
                'rates_eur' => 397.515735,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:03',
            ),
            82 => 
            array (
                'id' => 83,
                'name' => 'Laotian Kip',
                'alphacode' => 'LAK',
                'api_code' => 'USDLAK',
                'api_code_eur' => 'EURLAK',
                'rates' => 8380.00041,
                'rates_eur' => 9819.514859,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:03',
            ),
            83 => 
            array (
                'id' => 84,
                'name' => 'Lebanese Pound',
                'alphacode' => 'LBP',
                'api_code' => 'USDLBP',
                'api_code_eur' => 'EURLBP',
                'rates' => 1504.999673,
                'rates_eur' => 1763.949396,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:03',
            ),
            84 => 
            array (
                'id' => 85,
                'name' => 'Sri Lankan Rupee',
                'alphacode' => 'LKR',
                'api_code' => 'USDLKR',
                'api_code_eur' => 'EURLKR',
                'rates' => 159.550003,
                'rates_eur' => 186.123066,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:03',
            ),
            85 => 
            array (
                'id' => 86,
                'name' => 'Liberian Dollar',
                'alphacode' => 'LRD',
                'api_code' => 'USDLRD',
                'api_code_eur' => 'EURLRD',
                'rates' => 140.809998,
                'rates_eur' => 172.644381,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:03',
            ),
            86 => 
            array (
                'id' => 87,
                'name' => 'Lesotho Loti',
                'alphacode' => 'LSL',
                'api_code' => 'USDLSL',
                'api_code_eur' => 'EURLSL',
                'rates' => 13.649624,
                'rates_eur' => 15.963689,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:03',
            ),
            87 => 
            array (
                'id' => 88,
                'name' => 'Lithuanian Litas',
                'alphacode' => 'LTL',
                'api_code' => 'USDLTL',
                'api_code_eur' => 'EURLTL',
                'rates' => 3.048699,
                'rates_eur' => 3.57326,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:03',
            ),
            88 => 
            array (
                'id' => 89,
                'name' => 'Latvian Lats',
                'alphacode' => 'LVL',
                'api_code' => 'USDLVL',
                'api_code_eur' => 'EURLVL',
                'rates' => 0.62055,
                'rates_eur' => 0.727321,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:03',
            ),
            89 => 
            array (
                'id' => 90,
                'name' => 'Libyan Dinar',
                'alphacode' => 'LYD',
                'api_code' => 'USDLYD',
                'api_code_eur' => 'EURLYD',
                'rates' => 1.355797,
                'rates_eur' => 1.601269,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:03',
            ),
            90 => 
            array (
                'id' => 91,
                'name' => 'Moroccan Dirham',
                'alphacode' => 'MAD',
                'api_code' => 'USDMAD',
                'api_code_eur' => 'EURMAD',
                'rates' => 9.513496,
                'rates_eur' => 11.092845,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:03',
            ),
            91 => 
            array (
                'id' => 92,
                'name' => 'Moldovan Leu',
                'alphacode' => 'MDL',
                'api_code' => 'USDMDL',
                'api_code_eur' => 'EURMDL',
                'rates' => 16.684999,
                'rates_eur' => 19.832436,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:03',
            ),
            92 => 
            array (
                'id' => 93,
                'name' => 'Malagasy Ariary',
                'alphacode' => 'MGA',
                'api_code' => 'USDMGA',
                'api_code_eur' => 'EURMGA',
                'rates' => 3269.999988,
                'rates_eur' => 3832.635176,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:03',
            ),
            93 => 
            array (
                'id' => 94,
                'name' => 'Macedonian Denar',
                'alphacode' => 'MKD',
                'api_code' => 'USDMKD',
                'api_code_eur' => 'EURMKD',
                'rates' => 52.650002,
                'rates_eur' => 61.263548,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:03',
            ),
            94 => 
            array (
                'id' => 95,
                'name' => 'Myanma Kyat',
                'alphacode' => 'MMK',
                'api_code' => 'USDMMK',
                'api_code_eur' => 'EURMMK',
                'rates' => 1353.999509,
                'rates_eur' => 1622.130105,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:03',
            ),
            95 => 
            array (
                'id' => 96,
                'name' => 'Mongolian Tugrik',
                'alphacode' => 'MNT',
                'api_code' => 'USDMNT',
                'api_code_eur' => 'EURMNT',
                'rates' => 2419.000027,
                'rates_eur' => 2880.922128,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:03',
            ),
            96 => 
            array (
                'id' => 97,
                'name' => 'Macanese Pataca',
                'alphacode' => 'MOP',
                'api_code' => 'USDMOP',
                'api_code_eur' => 'EURMOP',
                'rates' => 8.083198,
                'rates_eur' => 9.473176,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:03',
            ),
            97 => 
            array (
                'id' => 98,
                'name' => 'Mauritanian Ouguiya',
                'alphacode' => 'MRO',
                'api_code' => 'USDMRO',
                'api_code_eur' => 'EURMRO',
                'rates' => 354.999991,
                'rates_eur' => 416.080811,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:03',
            ),
            98 => 
            array (
                'id' => 99,
                'name' => 'Mauritian Rupee',
                'alphacode' => 'MUR',
                'api_code' => 'USDMUR',
                'api_code_eur' => 'EURMUR',
                'rates' => 34.830002,
                'rates_eur' => 40.506381,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:03',
            ),
            99 => 
            array (
                'id' => 100,
                'name' => 'Maldivian Rufiyaa',
                'alphacode' => 'MVR',
                'api_code' => 'USDMVR',
                'api_code_eur' => 'EURMVR',
                'rates' => 15.570351,
                'rates_eur' => 18.249395,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:03',
            ),
            100 => 
            array (
                'id' => 101,
                'name' => 'Malawian Kwacha',
                'alphacode' => 'MWK',
                'api_code' => 'USDMWK',
                'api_code_eur' => 'EURMWK',
                'rates' => 713.450012,
                'rates_eur' => 836.205928,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:04',
            ),
            101 => 
            array (
                'id' => 102,
                'name' => 'Mexican Peso',
                'alphacode' => 'MXN',
                'api_code' => 'USDMXN',
                'api_code_eur' => 'EURMXN',
                'rates' => 20.568399,
                'rates_eur' => 23.354225,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:04',
            ),
            102 => 
            array (
                'id' => 103,
                'name' => 'Malaysian Ringgit',
                'alphacode' => 'MYR',
                'api_code' => 'USDMYR',
                'api_code_eur' => 'EURMYR',
                'rates' => 3.99497,
                'rates_eur' => 4.712856,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:04',
            ),
            103 => 
            array (
                'id' => 104,
                'name' => 'Mozambican Metical',
                'alphacode' => 'MZN',
                'api_code' => 'USDMZN',
                'api_code_eur' => 'EURMZN',
                'rates' => 58.709999,
                'rates_eur' => 68.82334,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:04',
            ),
            104 => 
            array (
                'id' => 105,
                'name' => 'Namibian Dollar',
                'alphacode' => 'NAD',
                'api_code' => 'USDNAD',
                'api_code_eur' => 'EURNAD',
                'rates' => 13.668011,
                'rates_eur' => 15.873217,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:04',
            ),
            105 => 
            array (
                'id' => 106,
                'name' => 'Nigerian Naira',
                'alphacode' => 'NGN',
                'api_code' => 'USDNGN',
                'api_code_eur' => 'EURNGN',
                'rates' => 358.000471,
                'rates_eur' => 419.597562,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:04',
            ),
            106 => 
            array (
                'id' => 107,
                'name' => 'Nicaraguan Córdoba',
                'alphacode' => 'NIO',
                'api_code' => 'USDNIO',
                'api_code_eur' => 'EURNIO',
                'rates' => 31.309999,
                'rates_eur' => 36.579979,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:04',
            ),
            107 => 
            array (
                'id' => 108,
                'name' => 'Norwegian Krone',
                'alphacode' => 'NOK',
                'api_code' => 'USDNOK',
                'api_code_eur' => 'EURNOK',
                'rates' => 8.11711,
                'rates_eur' => 9.488327,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:04',
            ),
            108 => 
            array (
                'id' => 109,
                'name' => 'Nepalese Rupee',
                'alphacode' => 'NPR',
                'api_code' => 'USDNPR',
                'api_code_eur' => 'EURNPR',
                'rates' => 108.519997,
                'rates_eur' => 126.863728,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:04',
            ),
            109 => 
            array (
                'id' => 110,
                'name' => 'New Zealand Dollar',
                'alphacode' => 'NZD',
                'api_code' => 'USDNZD',
                'api_code_eur' => 'EURNZD',
                'rates' => 1.441599,
                'rates_eur' => 1.699369,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:04',
            ),
            110 => 
            array (
                'id' => 111,
                'name' => 'Omani Rial',
                'alphacode' => 'OMR',
                'api_code' => 'USDOMR',
                'api_code_eur' => 'EUROMR',
                'rates' => 0.3849,
                'rates_eur' => 0.451128,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:04',
            ),
            111 => 
            array (
                'id' => 112,
                'name' => 'Panamanian Balboa',
                'alphacode' => 'PAB',
                'api_code' => 'USDPAB',
                'api_code_eur' => 'EURPAB',
                'rates' => 1.0,
                'rates_eur' => 1.17206,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:04',
            ),
            112 => 
            array (
                'id' => 113,
                'name' => 'Peruvian Nuevo Sol',
                'alphacode' => 'PEN',
                'api_code' => 'USDPEN',
                'api_code_eur' => 'EURPEN',
                'rates' => 3.275501,
                'rates_eur' => 3.8303,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:04',
            ),
            113 => 
            array (
                'id' => 114,
                'name' => 'Papua New Guinean Kina',
                'alphacode' => 'PGK',
                'api_code' => 'USDPGK',
                'api_code_eur' => 'EURPGK',
                'rates' => 3.240293,
                'rates_eur' => 3.799233,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:04',
            ),
            114 => 
            array (
                'id' => 115,
                'name' => 'Philippine Peso',
                'alphacode' => 'PHP',
                'api_code' => 'USDPHP',
                'api_code_eur' => 'EURPHP',
                'rates' => 53.380001,
                'rates_eur' => 62.646586,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:04',
            ),
            115 => 
            array (
                'id' => 116,
                'name' => 'Pakistani Rupee',
                'alphacode' => 'PKR',
                'api_code' => 'USDPKR',
                'api_code_eur' => 'EURPKR',
                'rates' => 118.489998,
                'rates_eur' => 142.358357,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:04',
            ),
            116 => 
            array (
                'id' => 117,
                'name' => 'Polish Zloty',
                'alphacode' => 'PLN',
                'api_code' => 'USDPLN',
                'api_code_eur' => 'EURPLN',
                'rates' => 3.699201,
                'rates_eur' => 4.347755,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:04',
            ),
            117 => 
            array (
                'id' => 118,
                'name' => 'Paraguayan Guarani',
                'alphacode' => 'PYG',
                'api_code' => 'USDPYG',
                'api_code_eur' => 'EURPYG',
                'rates' => 5668.600098,
                'rates_eur' => 6660.931969,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:04',
            ),
            118 => 
            array (
                'id' => 119,
                'name' => 'Qatari Rial',
                'alphacode' => 'QAR',
                'api_code' => 'USDQAR',
                'api_code_eur' => 'EURQAR',
                'rates' => 3.639797,
                'rates_eur' => 4.267822,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:05',
            ),
            119 => 
            array (
                'id' => 120,
                'name' => 'Romanian Leu',
                'alphacode' => 'RON',
                'api_code' => 'USDRON',
                'api_code_eur' => 'EURRON',
                'rates' => 4.010898,
                'rates_eur' => 4.664462,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:05',
            ),
            120 => 
            array (
                'id' => 121,
                'name' => 'Serbian Dinar',
                'alphacode' => 'RSD',
                'api_code' => 'USDRSD',
                'api_code_eur' => 'EURRSD',
                'rates' => 101.604401,
                'rates_eur' => 118.793398,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:05',
            ),
            121 => 
            array (
                'id' => 122,
                'name' => 'Russian Ruble',
                'alphacode' => 'RUB',
                'api_code' => 'USDRUB',
                'api_code_eur' => 'EURRUB',
                'rates' => 63.443001,
                'rates_eur' => 73.533844,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:05',
            ),
            122 => 
            array (
                'id' => 123,
                'name' => 'Rwandan Franc',
                'alphacode' => 'RWF',
                'api_code' => 'USDRWF',
                'api_code_eur' => 'EURRWF',
                'rates' => 849.429993,
                'rates_eur' => 995.582569,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:05',
            ),
            123 => 
            array (
                'id' => 124,
                'name' => 'Saudi Riyal',
                'alphacode' => 'SAR',
                'api_code' => 'USDSAR',
                'api_code_eur' => 'EURSAR',
                'rates' => 3.750204,
                'rates_eur' => 4.395339,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:05',
            ),
            124 => 
            array (
                'id' => 125,
                'name' => 'Solomon Islands Dollar',
                'alphacode' => 'SBD',
                'api_code' => 'USDSBD',
                'api_code_eur' => 'EURSBD',
                'rates' => 7.902602,
                'rates_eur' => 9.23313,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:05',
            ),
            125 => 
            array (
                'id' => 126,
                'name' => 'Seychellois Rupee',
                'alphacode' => 'SCR',
                'api_code' => 'USDSCR',
                'api_code_eur' => 'EURSCR',
                'rates' => 13.459637,
                'rates_eur' => 15.731335,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:05',
            ),
            126 => 
            array (
                'id' => 127,
                'name' => 'Sudanese Pound',
                'alphacode' => 'SDG',
                'api_code' => 'USDSDG',
                'api_code_eur' => 'EURSDG',
                'rates' => 17.955203,
                'rates_eur' => 21.044562,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:05',
            ),
            127 => 
            array (
                'id' => 128,
                'name' => 'Swedish Krona',
                'alphacode' => 'SEK',
                'api_code' => 'USDSEK',
                'api_code_eur' => 'EURSEK',
                'rates' => 8.81671,
                'rates_eur' => 10.358944,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:05',
            ),
            128 => 
            array (
                'id' => 129,
                'name' => 'Singapore Dollar',
                'alphacode' => 'SGD',
                'api_code' => 'USDSGD',
                'api_code_eur' => 'EURSGD',
                'rates' => 1.35127,
                'rates_eur' => 1.594974,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:05',
            ),
            129 => 
            array (
                'id' => 130,
                'name' => 'Saint Helena Pound',
                'alphacode' => 'SHP',
                'api_code' => 'USDSHP',
                'api_code_eur' => 'EURSHP',
                'rates' => 0.754959,
                'rates_eur' => 0.88244,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:05',
            ),
            130 => 
            array (
                'id' => 131,
                'name' => 'Sierra Leonean Leone',
                'alphacode' => 'SLL',
                'api_code' => 'USDSLL',
                'api_code_eur' => 'EURSLL',
                'rates' => 7939.999757,
                'rates_eur' => 9353.035758,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:05',
            ),
            131 => 
            array (
                'id' => 132,
                'name' => 'Somali Shilling',
                'alphacode' => 'SOS',
                'api_code' => 'USDSOS',
                'api_code_eur' => 'EURSOS',
                'rates' => 561.999832,
                'rates_eur' => 670.418057,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:05',
            ),
            132 => 
            array (
                'id' => 133,
                'name' => 'Surinamese Dollar',
                'alphacode' => 'SRD',
                'api_code' => 'USDSRD',
                'api_code_eur' => 'EURSRD',
                'rates' => 7.429821,
                'rates_eur' => 8.708409,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:05',
            ),
            133 => 
            array (
                'id' => 134,
                'name' => 'São Tomé and Príncipe Dobra',
                'alphacode' => 'STD',
                'api_code' => 'USDSTD',
                'api_code_eur' => 'EURSTD',
                'rates' => 21064.400391,
                'rates_eur' => 24509.640859,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:05',
            ),
            134 => 
            array (
                'id' => 135,
                'name' => 'Salvadoran Colón',
                'alphacode' => 'SVC',
                'api_code' => 'USDSVC',
                'api_code_eur' => 'EURSVC',
                'rates' => 8.74996,
                'rates_eur' => 10.255934,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:05',
            ),
            135 => 
            array (
                'id' => 136,
                'name' => 'Syrian Pound',
                'alphacode' => 'SYP',
                'api_code' => 'USDSYP',
                'api_code_eur' => 'EURSYP',
                'rates' => 514.97998,
                'rates_eur' => 603.587224,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:05',
            ),
            136 => 
            array (
                'id' => 137,
                'name' => 'Swazi Lilangeni',
                'alphacode' => 'SZL',
                'api_code' => 'USDSZL',
                'api_code_eur' => 'EURSZL',
                'rates' => 13.668023,
                'rates_eur' => 15.873233,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:05',
            ),
            137 => 
            array (
                'id' => 138,
                'name' => 'Thai Baht',
                'alphacode' => 'THB',
                'api_code' => 'USDTHB',
                'api_code_eur' => 'EURTHB',
                'rates' => 32.660999,
                'rates_eur' => 38.629953,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:06',
            ),
            138 => 
            array (
                'id' => 139,
                'name' => 'Tajikistani Somoni',
                'alphacode' => 'TJS',
                'api_code' => 'USDTJS',
                'api_code_eur' => 'EURTJS',
                'rates' => 9.090697,
                'rates_eur' => 10.707237,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:06',
            ),
            139 => 
            array (
                'id' => 140,
                'name' => 'Turkmenistani Manat',
                'alphacode' => 'TMT',
                'api_code' => 'USDTMT',
                'api_code_eur' => 'EURTMT',
                'rates' => 3.4,
                'rates_eur' => 3.985003,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:06',
            ),
            140 => 
            array (
                'id' => 141,
                'name' => 'Tunisian Dinar',
                'alphacode' => 'TND',
                'api_code' => 'USDTND',
                'api_code_eur' => 'EURTND',
                'rates' => 2.589796,
                'rates_eur' => 3.038911,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:06',
            ),
            141 => 
            array (
                'id' => 142,
                'name' => 'Tongan Paʻanga',
                'alphacode' => 'TOP',
                'api_code' => 'USDTOP',
                'api_code_eur' => 'EURTOP',
                'rates' => 2.303803,
                'rates_eur' => 2.703958,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:06',
            ),
            142 => 
            array (
                'id' => 143,
                'name' => 'Turkish Lira',
                'alphacode' => 'TRY',
                'api_code' => 'USDTRY',
                'api_code_eur' => 'EURTRY',
                'rates' => 4.706502,
                'rates_eur' => 5.487462,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:06',
            ),
            143 => 
            array (
                'id' => 144,
                'name' => 'Trinidad and Tobago Dollar',
                'alphacode' => 'TTD',
                'api_code' => 'USDTTD',
                'api_code_eur' => 'EURTTD',
                'rates' => 6.649499,
                'rates_eur' => 7.793612,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:06',
            ),
            144 => 
            array (
                'id' => 145,
                'name' => 'New Taiwan Dollar',
                'alphacode' => 'TWD',
                'api_code' => 'USDTWD',
                'api_code_eur' => 'EURTWD',
                'rates' => 30.144987,
                'rates_eur' => 35.657611,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:06',
            ),
            145 => 
            array (
                'id' => 146,
                'name' => 'Tanzanian Shilling',
                'alphacode' => 'TZS',
                'api_code' => 'USDTZS',
                'api_code_eur' => 'EURTZS',
                'rates' => 2267.999722,
                'rates_eur' => 2658.231099,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:06',
            ),
            146 => 
            array (
                'id' => 147,
                'name' => 'Ukrainian Hryvnia',
                'alphacode' => 'UAH',
                'api_code' => 'USDUAH',
                'api_code_eur' => 'EURUAH',
                'rates' => 26.315001,
                'rates_eur' => 30.649228,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:06',
            ),
            147 => 
            array (
                'id' => 148,
                'name' => 'Ugandan Shilling',
                'alphacode' => 'UGX',
                'api_code' => 'USDUGX',
                'api_code_eur' => 'EURUGX',
                'rates' => 3847.000256,
                'rates_eur' => 4532.354214,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:06',
            ),
            148 => 
            array (
                'id' => 149,
                'name' => 'United States Dollar',
                'alphacode' => 'USD',
                'api_code' => 'USDUSD',
                'api_code_eur' => 'EURUSD',
                'rates' => 1.0,
                'rates_eur' => 1.17206,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:06',
            ),
            149 => 
            array (
                'id' => 150,
                'name' => 'Uruguayan Peso',
                'alphacode' => 'UYU',
                'api_code' => 'USDUYU',
                'api_code_eur' => 'EURUYU',
                'rates' => 31.579875,
                'rates_eur' => 36.825787,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:06',
            ),
            150 => 
            array (
                'id' => 151,
                'name' => 'Uzbekistan Som',
                'alphacode' => 'UZS',
                'api_code' => 'USDUZS',
                'api_code_eur' => 'EURUZS',
                'rates' => 7864.999707,
                'rates_eur' => 9224.108793,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:06',
            ),
            151 => 
            array (
                'id' => 152,
                'name' => 'Venezuelan Bolívar Fuerte',
                'alphacode' => 'VEF',
                'api_code' => 'USDVEF',
                'api_code_eur' => 'EURVEF',
                'rates' => 79800.000258,
                'rates_eur' => 112224.705585,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:06',
            ),
            152 => 
            array (
                'id' => 153,
                'name' => 'Vietnamese Dong',
                'alphacode' => 'VND',
                'api_code' => 'USDVND',
                'api_code_eur' => 'EURVND',
                'rates' => 22834.0,
                'rates_eur' => 26834.304307,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:06',
            ),
            153 => 
            array (
                'id' => 154,
                'name' => 'Vanuatu Vatu',
                'alphacode' => 'VUV',
                'api_code' => 'USDVUV',
                'api_code_eur' => 'EURVUV',
                'rates' => 108.050003,
                'rates_eur' => 126.746523,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:06',
            ),
            154 => 
            array (
                'id' => 155,
                'name' => 'Samoan Tala',
                'alphacode' => 'WST',
                'api_code' => 'USDWST',
                'api_code_eur' => 'EURWST',
                'rates' => 2.592902,
                'rates_eur' => 3.044544,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:06',
            ),
            155 => 
            array (
                'id' => 156,
                'name' => 'CFA Franc BEAC',
                'alphacode' => 'XAF',
                'api_code' => 'USDXAF',
                'api_code_eur' => 'EURXAF',
                'rates' => 563.330017,
                'rates_eur' => 655.544647,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:06',
            ),
            156 => 
            array (
                'id' => 157,
            'name' => 'Silver (troy ounce)',
                'alphacode' => 'XAG',
                'api_code' => 'USDXAG',
                'api_code_eur' => 'EURXAG',
                'rates' => 0.060601,
                'rates_eur' => 0.071842,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:07',
            ),
            157 => 
            array (
                'id' => 158,
            'name' => 'Gold (troy ounce)',
                'alphacode' => 'XAU',
                'api_code' => 'USDXAU',
                'api_code_eur' => 'EURXAU',
                'rates' => 0.00078,
                'rates_eur' => 0.000927,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:07',
            ),
            158 => 
            array (
                'id' => 159,
                'name' => 'East Caribbean Dollar',
                'alphacode' => 'XCD',
                'api_code' => 'USDXCD',
                'api_code_eur' => 'EURXCD',
                'rates' => 2.69968,
                'rates_eur' => 3.170112,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:07',
            ),
            159 => 
            array (
                'id' => 160,
                'name' => 'Special Drawing Rights',
                'alphacode' => 'XDR',
                'api_code' => 'USDXDR',
                'api_code_eur' => 'EURXDR',
                'rates' => 0.708618,
                'rates_eur' => 0.830632,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:07',
            ),
            160 => 
            array (
                'id' => 161,
                'name' => 'CFA Franc BCEAO',
                'alphacode' => 'XOF',
                'api_code' => 'USDXOF',
                'api_code_eur' => 'EURXOF',
                'rates' => 563.330017,
                'rates_eur' => 655.544647,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:07',
            ),
            161 => 
            array (
                'id' => 162,
                'name' => 'CFP Franc',
                'alphacode' => 'XPF',
                'api_code' => 'USDXPF',
                'api_code_eur' => 'EURXPF',
                'rates' => 102.580241,
                'rates_eur' => 119.364948,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:07',
            ),
            162 => 
            array (
                'id' => 163,
                'name' => 'Yemeni Rial',
                'alphacode' => 'YER',
                'api_code' => 'USDYER',
                'api_code_eur' => 'EURYER',
                'rates' => 249.850006,
                'rates_eur' => 292.780489,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:07',
            ),
            163 => 
            array (
                'id' => 164,
                'name' => 'South African Rand',
                'alphacode' => 'ZAR',
                'api_code' => 'USDZAR',
                'api_code_eur' => 'EURZAR',
                'rates' => 13.6682,
                'rates_eur' => 15.873317,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:07',
            ),
            164 => 
            array (
                'id' => 165,
            'name' => 'Zambian Kwacha (pre-2013)',
                'alphacode' => 'ZMK',
                'api_code' => 'USDZMK',
                'api_code_eur' => 'EURZMK',
                'rates' => 9001.200967,
                'rates_eur' => 10549.944101,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:07',
            ),
            165 => 
            array (
                'id' => 166,
                'name' => 'Zambian Kwacha',
                'alphacode' => 'ZMW',
                'api_code' => 'USDZMW',
                'api_code_eur' => 'EURZMW',
                'rates' => 9.910165,
                'rates_eur' => 11.497736,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:07',
            ),
            166 => 
            array (
                'id' => 167,
                'name' => 'Zimbabwean Dollar',
                'alphacode' => 'ZWL',
                'api_code' => 'USDZWL',
                'api_code_eur' => 'EURZWL',
                'rates' => 322.355011,
                'rates_eur' => 377.819282,
                'created_at' => NULL,
                'updated_at' => '2018-06-26 03:11:07',
            ),
        ));
        
        
    }
}