CREATE  PROCEDURE barracuda_select_request_fcl(IN date_start VARCHAR(255),IN date_end VARCHAR(255))
SELECT nr.id, cpu.name AS company_user,cpu.options->'$.tier' AS tier, nr.namecontract, nr.numbercontract, REPLACE((CASE WHEN nr.data->'$.group_containers.name' != '' THEN nr.data->'$.group_containers.name' ELSE '/DRY' END),'"','') AS equipment, REPLACE(REPLACE(nr.data->'$.containers[*].code','[',''),']','') as containers, dr.name AS direction, nr.namefile, (SELECT (CASE WHEN COUNT(btmp.id) > 0 THEN 1 ELSE 0 END) FROM barracuda_templates btmp WHERE FIND_IN_SET(btmp.direction_id,(CASE WHEN nr.direction_id > 2 THEN '1,2,3' ELSE CONCAT(CAST(nr.direction_id AS CHAR),',','3') END)) AND btmp.equipment_id=(CASE WHEN nr.data->'$.group_containers.id' > 0  THEN nr.data->'$.group_containers.id' ELSE 1 END) AND FIND_IN_SET(btmp.carrier_id,(SELECT GROUP_CONCAT( DISTINCT(cr.id) SEPARATOR ',') FROM request_fcl_carriers rcarr INNER JOIN carriers cr ON rcarr.carrier_id=cr.id WHERE nr.id=rcarr.request_id))) AS carrier_imp_true, (SELECT GROUP_CONCAT( DISTINCT(cr.name) SEPARATOR ', ')  FROM request_fcl_carriers rcarr INNER JOIN carriers cr ON rcarr.carrier_id=cr.id WHERE nr.id=rcarr.request_id) AS carriers, nr.validation,nr.created,CONCAT(us.name,CONCAT(' ',us.lastname)) AS user, (CASE WHEN nr.time_total <> '' THEN nr.time_total  ELSE 'N/A' END) AS time_elapsed, nr.username_load, nr.status, nr.contract_id AS contract, cts.validator AS validator_contract, nr.erased_contract, (CASE WHEN brqm.in_course THEN 1 ELSE 0 END) AS bc_rq_mappin_status, (CASE WHEN (SELECT COUNT(id) from accounts_import_cfcl account WHERE account.request_id=nr.id AND account.request_dp_id IS NOT NULL) > 0 THEN 2 WHEN (SELECT COUNT(id) from possible_duplicates_fcl pdp_fcl WHERE pdp_fcl.request_id=nr.id) > 0 THEN 1 ELSE 0 END ) AS duplicate, (CASE WHEN nr.template_id  THEN 1 ELSE 0 END) AS template FROM newcontractrequests nr INNER JOIN company_users cpu ON nr.company_user_id = cpu.id LEFT JOIN directions dr ON  dr.id = nr.direction_id LEFT JOIN contracts cts ON nr.contract_id=cts.id INNER JOIN users us ON nr.user_id=us.id LEFT JOIN barracuda_request_fcl_mapping brqm ON  brqm.request_id = nr.id WHERE nr.status_erased <> 1 AND nr.created BETWEEN date_start AND date_end ORDER BY nr.id DESC;

CREATE  PROCEDURE barracuda_select_request_lcl(IN date_start VARCHAR(255),IN date_end VARCHAR(255))
SELECT nr.id, cpu.name AS company_user, cpu.options->'$.tier' AS tier, nr.namecontract, dr.name AS direction, (SELECT GROUP_CONCAT( DISTINCT(cr.name) SEPARATOR ', ')  FROM request_lcl_carriers rcarr INNER JOIN carriers cr ON rcarr.carrier_id=cr.id WHERE nr.id=rcarr.request_id) AS carriers, nr.validation, nr.created, CONCAT(us.name,CONCAT(' ',us.lastname)) AS user, (CASE WHEN nr.time_total <> '' THEN nr.time_total  ELSE 'N/A' END) AS time_elapsed, nr.username_load, nr.status, nr.contract_id AS contract, (CASE WHEN (SELECT COUNT(id) FROM accounts_import_clcl account WHERE account.requestlcl_id=nr.id AND account.request_dp_id IS NOT NULL) > 0 THEN 2 WHEN (SELECT COUNT(id) FROM possible_duplicates_lcl pdp_lcl WHERE pdp_lcl.request_id=nr.id) > 0 THEN 1 ELSE 0 END ) AS duplicate,(CASE WHEN nr.template_id  THEN 1 ELSE 0 END) AS template, (SELECT (CASE WHEN COUNT(btmp.id) > 0 THEN 1 ELSE 0 END) FROM barracuda_templates btmp WHERE FIND_IN_SET(btmp.direction_id, (CASE WHEN nr.direction_id > 2 THEN '1,2,3' ELSE CONCAT(CAST(nr.direction_id AS CHAR),',','3') END)) AND FIND_IN_SET(btmp.carrier_id,(SELECT GROUP_CONCAT( DISTINCT(cr.id) SEPARATOR ',') FROM request_lcl_carriers rcarr INNER JOIN carriers cr ON rcarr.carrier_id=cr.id WHERE nr.id=rcarr.request_id))) as carrier_imp_true,(CASE WHEN brqm.in_course THEN 1 ELSE 0 END) as bc_rq_mappin_status FROM new_contract_request_lcl nr INNER JOIN company_users cpu ON nr.company_user_id = cpu.id LEFT JOIN directions dr ON  dr.id = nr.direction_id INNER JOIN users us ON nr.user_id=us.id LEFT JOIN barracuda_request_lcl_mapping brqm ON brqm.request_id = nr.id WHERE nr.created BETWEEN date_start AND date_end;

CREATE  PROCEDURE proc_account_fcl(IN date_start VARCHAR(30),IN date_end VARCHAR(30))
SELECT ac.id,ac.name,ac.namefile,ac.date,IFNULL(ac.request_id, 'manual') as request_id,IF(STRCMP(ct.status,'publish') =0,'published',IFNULL(ct.status, 'Contract erased')) as status,comp.name as company_name,ct.id as contract_id,ac.request_dp_id FROM accounts_import_cfcl ac LEFT OUTER JOIN contracts ct on ac.id = ct.account_id inner join company_users comp on ac.company_user_id = comp.id WHERE ac.date BETWEEN date_start AND date_end;

CREATE  PROCEDURE proc_account_lcl()
SELECT ac.id,ac.name,ac.date, IFNULL(ac.requestlcl_id, 'manual') as request_id  , IFNULL(ct.status, 'Contract erased') as status ,comp.name as company_name,ct.id as contract_id FROM accounts_import_clcl ac inner join contracts_lcl ct on ac.id = ct.account_id inner join company_users comp on ac.company_user_id = comp.id;

CREATE  PROCEDURE proc_duplicado_globalcharge_fcl(IN gp_global_dp_id INT)
SELECT gbdp.id as duplicate_id, gbdp.global_id as global_ref, gb.id as global_duplicated_id, (SELECT GROUP_CONCAT(DISTINCT(har.display_name) SEPARATOR ', ') FROM globalcharport gbp INNER JOIN harbors har on har.id = gbp.port_orig WHERE gbp.globalcharge_id = gb.id ) as port_orig , (SELECT GROUP_CONCAT(DISTINCT(har.display_name) SEPARATOR ', ') FROM globalcharport gbp INNER JOIN harbors har on har.id = gbp.port_dest WHERE gbp.globalcharge_id = gb.id ) as port_dest, (SELECT GROUP_CONCAT(DISTINCT(coun.name) SEPARATOR ', ') FROM globalcharcountry gbCD INNER JOIN countries coun on coun.id = gbCD.country_orig WHERE gbCD.globalcharge_id = gb.id ) as country_orig , (SELECT GROUP_CONCAT(DISTINCT(counD.name) SEPARATOR ', ') FROM globalcharcountry gbCD INNER JOIN countries counD on counD.id = gbCD.country_dest WHERE gbCD.globalcharge_id = gb.id ) as country_dest , (SELECT GROUP_CONCAT(DISTINCT(carr.name) SEPARATOR ', ') FROM globalcharcarrier gbC INNER JOIN carriers carr on carr.id = gbC.carrier_id WHERE gbC.globalcharge_id = gb.id ) as carrier,sg.name as surcharges, td.description as typedestiny, ct.name as calculationtype, gb.ammount, gb.validity,gb.expire, cy.alphacode AS currency, cmpu.name as company_user, gb.account_importation_globalcharge_id FROM global_duplicateds gbdp INNER JOIN globalcharges gb ON gb.id=gbdp.global_dp_id INNER JOIN surcharges sg ON gb.surcharge_id = sg.id INNER JOIN typedestiny td ON gb.typedestiny_id = td.id INNER JOIN calculationtype ct ON gb.calculationtype_id = ct.id INNER JOIN currency cy ON gb.currency_id = cy.id INNER JOIN company_users cmpu ON gb.company_user_id = cmpu.id WHERE gbdp.gp_global_dp_id =gp_global_dp_id;

CREATE  PROCEDURE proc_fails_rates_lcl(IN contractlcl_id_sc INT)
SELECT * FROM failes_rate_lcl WHERE contractlcl_id = contractlcl_id_sc;

CREATE  PROCEDURE proc_fails_surchargers_fcl(IN contact_id_sc INT)
SELECT * FROM failes_surcharges WHERE contract_id=contact_id_sc;

CREATE  PROCEDURE proc_fail_rates_fcl(In contract_id_sc INT)
SELECT * FROM failes_rates WHERE contract_id = contract_id_sc;

CREATE  PROCEDURE proc_globalcharge_id(IN globalID INT)
SELECT gb.id, (SELECT GROUP_CONCAT(DISTINCT(har.display_name) SEPARATOR ' | ') FROM globalcharport gbp INNER JOIN harbors har on har.id = gbp.port_orig WHERE gbp.globalcharge_id = gb.id ) as port_orig , (SELECT GROUP_CONCAT(DISTINCT(har.display_name) SEPARATOR ' | ') FROM globalcharport gbp INNER JOIN harbors har on har.id = gbp.port_dest WHERE gbp.globalcharge_id = gb.id ) as port_dest, (SELECT GROUP_CONCAT(DISTINCT(coun.name) SEPARATOR ' | ') FROM globalcharcountry gbCD INNER JOIN countries coun on coun.id = gbCD.country_orig WHERE gbCD.globalcharge_id = gb.id ) as country_orig , (SELECT GROUP_CONCAT(DISTINCT(counD.name) SEPARATOR ' | ') FROM globalcharcountry gbCD INNER JOIN countries counD on counD.id = gbCD.country_dest WHERE gbCD.globalcharge_id = gb.id ) as country_dest , (SELECT GROUP_CONCAT(DISTINCT(carr.name) SEPARATOR ' | ') FROM globalcharcarrier gbC INNER JOIN carriers carr on carr.id = gbC.carrier_id WHERE gbC.globalcharge_id = gb.id ) as carrier, sg.name as surcharges, td.description as typedestiny, ct.name as calculationtype, gb.ammount, gb.validity,gb.expire, cy.alphacode AS currency, cmpu.name as company_user, gb.account_importation_globalcharge_id FROM globalcharges gb INNER JOIN surcharges sg ON gb.surcharge_id = sg.id INNER JOIN typedestiny td ON gb.typedestiny_id = td.id INNER JOIN calculationtype ct ON gb.calculationtype_id = ct.id INNER JOIN currency cy ON gb.currency_id = cy.id INNER JOIN company_users cmpu ON gb.company_user_id = cmpu.id WHERE gb.id = globalID;

CREATE  PROCEDURE proc_harbors()
SELECT har.id ,har.hierarchy ,har.name , har.code, har.display_name, har.coordinates , har.varation , coun.name as country_id FROM harbors as har inner join countries coun on har.country_id = coun.id;

CREATE  PROCEDURE proc_localchar(IN idcontract INT)
select lc.id, lc.contract_id, sr.name as surcharge,(SELECT GROUP_CONCAT(DISTINCT(har.display_name) SEPARATOR ', ') FROM localcharports lcP INNER JOIN harbors har on har.id = lcP.port_orig WHERE lcP.localcharge_id = lc.id ) as port_orig , (SELECT GROUP_CONCAT(DISTINCT(har.display_name) SEPARATOR ', ') FROM localcharports lcP INNER JOIN harbors har on har.id = lcP.port_dest WHERE lcP.localcharge_id = lc.id ) as port_dest, (SELECT GROUP_CONCAT(DISTINCT(coun.name) SEPARATOR ', ') FROM localcharcountry lcCO INNER JOIN countries coun on coun.id = lcCO.country_orig WHERE lcCO.localcharge_id = lc.id ) as country_orig ,(SELECT GROUP_CONCAT(DISTINCT(counD.name) SEPARATOR ', ') FROM localcharcountry lcCD INNER JOIN countries counD on counD.id = lcCD.country_dest WHERE lcCD.localcharge_id = lc.id ) as country_dest ,td.description changetype,(SELECT GROUP_CONCAT(DISTINCT(carr.name) SEPARATOR ', ') FROM localcharcarriers lcC INNER JOIN carriers carr on carr.id = lcC.carrier_id WHERE lcC.localcharge_id = lc.id ) as carrier,ctype.name calculation_type,cur.alphacode as currency,lc.ammount from localcharges lc INNER JOIN surcharges sr on sr.id = lc.surcharge_id INNER JOIN typedestiny td on td.id = lc.typedestiny_id INNER JOIN currency cur on cur.id = lc.currency_id INNER JOIN calculationtype ctype on ctype.id = lc.calculationtype_id WHERE lc.contract_id = idcontract;

CREATE  PROCEDURE proc_localchar_lcl(IN idcontract INT)
select lc.id, lc.contractlcl_id, sr.name as surcharge,(SELECT GROUP_CONCAT(DISTINCT(har.display_name) SEPARATOR ', ') FROM localcharports_lcl lcP INNER JOIN harbors har on har.id = lcP.port_orig WHERE lcP.localchargelcl_id = lc.id ) as port_orig , (SELECT GROUP_CONCAT(DISTINCT(har.display_name) SEPARATOR ', ') FROM localcharports_lcl lcP INNER JOIN harbors har on har.id = lcP.port_dest WHERE lcP.localchargelcl_id = lc.id ) as port_dest, (SELECT GROUP_CONCAT(DISTINCT(coun.name) SEPARATOR ', ') FROM localcharcountry_lcl lcCO INNER JOIN countries coun on coun.id = lcCO.country_orig WHERE lcCO.localchargelcl_id = lc.id ) as country_orig ,(SELECT GROUP_CONCAT(DISTINCT(counD.name) SEPARATOR ', ') FROM localcharcountry_lcl lcCD INNER JOIN countries counD on counD.id = lcCD.country_dest WHERE lcCD.localchargelcl_id = lc.id ) as country_dest ,td.description changetype,(SELECT GROUP_CONCAT(DISTINCT(carr.name) SEPARATOR ', ') FROM localcharcarriers_lcl lcC INNER JOIN carriers carr on carr.id = lcC.carrier_id WHERE lcC.localchargelcl_id = lc.id ) as carrier,ctype.name calculation_type,cur.alphacode as currency,lc.ammount,lc.minimum  from localcharges_lcl lc INNER JOIN surcharges sr on sr.id = lc.surcharge_id INNER JOIN typedestiny td on td.id = lc.typedestiny_id INNER JOIN currency cur on cur.id = lc.currency_id INNER JOIN calculationtypelcl ctype on ctype.id = lc.calculationtypelcl_id WHERE lc.contractlcl_id = idcontract;

CREATE  PROCEDURE proc_master_surcharge()
SELECT ms.id,sg.name,car.name as carrier, car.id as carrier_id,td.description as typedestiny,td.id as typedestiny_id, ct.name AS calculationtype, ct.id as calculationtype_id,dr.name as direction, dr.id as direction_id, gc.id as equiment_id, IFNULL(gc.name, 'ALL') AS equiment FROM master_surcharges ms INNER JOIN surcharges sg ON ms.surcharge_id=sg.id INNER JOIN carriers car ON ms.carrier_id = car.id INNER JOIN typedestiny td ON ms.typedestiny_id=td.id INNER JOIN calculationtype ct ON ms.calculationtype_id=ct.id INNER JOIN directions dr ON ms.direction_id=dr.id LEFT JOIN group_containers gc ON ms.group_container_id = gc.id;

CREATE  PROCEDURE proc_rates_fcl(IN contract_id INT)
SELECT rt.id,hb_or.name as origin,hb_de.name as destiny,car.name as carrier,twuenty,forty,fortyhc,fortynor,fortyfive,containers,cur.alphacode as currency FROM rates rt    INNER JOIN harbors hb_or ON rt.origin_port=hb_or.id INNER JOIN harbors hb_de ON rt.destiny_port=hb_de.id INNER JOIN carriers car ON rt.carrier_id=car.id INNER JOIN currency cur ON rt.currency_id=cur.id WHERE rt.contract_id=contract_id;

CREATE  PROCEDURE proc_transit_times()
SELECT tt.id,hbori.name as origin,hbdes.name as destiny,carr.name AS carrier, sht.name as destination_type,transit_time,via FROM transit_times tt INNER JOIN harbors hbori ON tt.origin_id = hbori.id INNER JOIN harbors hbdes ON tt.destination_id = hbdes.id INNER JOIN carriers carr ON tt.carrier_id = carr.id INNER JOIN destination_types sht ON tt.service_id = sht.id;

CREATE  PROCEDURE select_for_acount_globalcharger_lcl(IN acount_id INT)
SELECT gbl.id, (SELECT GROUP_CONCAT(DISTINCT(har.display_name) SEPARATOR ' | ') FROM globalcharports_lcl gbp INNER JOIN harbors har on har.id = gbp.port_orig WHERE gbp.globalchargelcl_id = gbl.id ) as port_orig, (SELECT GROUP_CONCAT(DISTINCT(har.display_name) SEPARATOR ' | ') FROM globalcharports_lcl gbp INNER JOIN harbors har on har.id = gbp.port_dest WHERE gbp.globalchargelcl_id = gbl.id ) as port_dest, (SELECT GROUP_CONCAT(DISTINCT(coun.name) SEPARATOR ' | ') FROM globalcharcountry_lcl gbCD INNER JOIN countries coun on coun.id = gbCD.country_orig WHERE gbCD.globalchargelcl_id = gbl.id ) as country_orig , (SELECT GROUP_CONCAT(DISTINCT(counD.name) SEPARATOR ' | ') FROM globalcharcountry_lcl gbCD INNER JOIN countries counD on counD.id = gbCD.country_dest WHERE gbCD.globalchargelcl_id = gbl.id ) as country_dest, (SELECT GROUP_CONCAT(DISTINCT(carr.name) SEPARATOR ' | ') FROM globalcharcarriers_lcl gbC INNER JOIN carriers carr on carr.id = gbC.carrier_id WHERE gbC.globalchargelcl_id = gbl.id ) as carrier, sg.name as surcharges, td.description as typedestiny, ct.name as calculationtype, gbl.ammount, gbl.minimum, gbl.validity,gbl.expire, cy.alphacode AS currency, cmpu.name as company_user FROM globalcharges_lcl gbl INNER JOIN surcharges sg ON gbl.surcharge_id = sg.id INNER JOIN typedestiny td ON gbl.typedestiny_id = td.id INNER JOIN calculationtypelcl ct ON gbl.calculationtypelcl_id = ct.id INNER JOIN currency cy ON gbl.currency_id = cy.id INNER JOIN company_users cmpu ON gbl.company_user_id = cmpu.id WHERE gbl.account_imp_gclcl_id = acount_id;

CREATE  PROCEDURE select_for_company_globalcharger(IN company_user_id INT)
SELECT gb.id, (SELECT GROUP_CONCAT(DISTINCT(har.display_name) SEPARATOR ' | ') FROM globalcharport gbp INNER JOIN harbors har on har.id = gbp.port_orig WHERE gbp.globalcharge_id = gb.id ) as port_orig , (SELECT GROUP_CONCAT(DISTINCT(har.display_name) SEPARATOR ' | ') FROM globalcharport gbp INNER JOIN harbors har on har.id = gbp.port_dest WHERE gbp.globalcharge_id = gb.id ) as port_dest, (SELECT GROUP_CONCAT(DISTINCT(coun.name) SEPARATOR ' | ') FROM globalcharcountry gbCD INNER JOIN countries coun on coun.id = gbCD.country_orig WHERE gbCD.globalcharge_id = gb.id ) as country_orig , (SELECT GROUP_CONCAT(DISTINCT(counD.name) SEPARATOR ' | ') FROM globalcharcountry gbCD INNER JOIN countries counD on counD.id = gbCD.country_dest WHERE gbCD.globalcharge_id = gb.id ) as country_dest, (SELECT GROUP_CONCAT(DISTINCT(portPC.name) SEPARATOR ' | ') FROM global_char_port_countries gcPC INNER JOIN harbors portPC on portPC.id = gcPC.port_orig WHERE gcPC.globalcharge_id = gb.id ) as portcountry_orig , (SELECT GROUP_CONCAT(DISTINCT(counPC.name) SEPARATOR ' | ') FROM global_char_port_countries gbPCd INNER JOIN countries counPC on counPC.id = gbPCd.country_dest WHERE gbPCd.globalcharge_id = gb.id ) as portcountry_dest ,(SELECT GROUP_CONCAT(DISTINCT(counCP.name) SEPARATOR ' | ') FROM global_char_country_ports gbCP INNER JOIN countries counCP on counCP.id = gbCP.country_orig WHERE gbCP.globalcharge_id = gb.id ) as countryport_orig , (SELECT GROUP_CONCAT(DISTINCT(counCPd.name) SEPARATOR ' | ') FROM global_char_country_ports gbCPd INNER JOIN harbors counCPd on counCPd.id = gbCPd.port_dest WHERE gbCPd.globalcharge_id = gb.id ) as countryport_dest ,(SELECT GROUP_CONCAT(DISTINCT(carr.name) SEPARATOR ' | ') FROM globalcharcarrier gbC INNER JOIN carriers carr on carr.id = gbC.carrier_id WHERE gbC.globalcharge_id = gb.id ) as carrier, sg.name as surcharges, td.description as typedestiny, ct.name as calculationtype, gb.ammount, gb.validity,gb.expire, cy.alphacode AS currency, cmpu.name as company_user, gb.account_importation_globalcharge_id FROM globalcharges gb INNER JOIN surcharges sg ON gb.surcharge_id = sg.id INNER JOIN typedestiny td ON gb.typedestiny_id = td.id INNER JOIN calculationtype ct ON gb.calculationtype_id = ct.id INNER JOIN currency cy ON gb.currency_id = cy.id INNER JOIN company_users cmpu ON gb.company_user_id = cmpu.id WHERE gb.company_user_id = company_user_id;

CREATE  PROCEDURE select_for_company_globalcharger_lcl(IN company_user_id int)
SELECT gbl.id, (SELECT GROUP_CONCAT(DISTINCT(har.display_name) SEPARATOR ' | ') FROM globalcharports_lcl gbp INNER JOIN harbors har on har.id = gbp.port_orig WHERE gbp.globalchargelcl_id = gbl.id ) as port_orig, (SELECT GROUP_CONCAT(DISTINCT(har.display_name) SEPARATOR ' | ') FROM globalcharports_lcl gbp INNER JOIN harbors har on har.id = gbp.port_dest WHERE gbp.globalchargelcl_id = gbl.id ) as port_dest, (SELECT GROUP_CONCAT(DISTINCT(coun.name) SEPARATOR ' | ') FROM globalcharcountry_lcl gbCD INNER JOIN countries coun on coun.id = gbCD.country_orig WHERE gbCD.globalchargelcl_id = gbl.id ) as country_orig , (SELECT GROUP_CONCAT(DISTINCT(counD.name) SEPARATOR ' | ') FROM globalcharcountry_lcl gbCD INNER JOIN countries counD on counD.id = gbCD.country_dest WHERE gbCD.globalchargelcl_id = gbl.id ) as country_dest, (SELECT GROUP_CONCAT(DISTINCT(carr.name) SEPARATOR ' | ') FROM globalcharcarriers_lcl gbC INNER JOIN carriers carr on carr.id = gbC.carrier_id WHERE gbC.globalchargelcl_id = gbl.id ) as carrier, sg.name as surcharges, td.description as typedestiny, ct.name as calculationtype, gbl.ammount, gbl.minimum, gbl.validity,gbl.expire, cy.alphacode AS currency, cmpu.name as company_user FROM globalcharges_lcl gbl INNER JOIN surcharges sg ON gbl.surcharge_id = sg.id INNER JOIN typedestiny td ON gbl.typedestiny_id = td.id INNER JOIN calculationtypelcl ct ON gbl.calculationtypelcl_id = ct.id INNER JOIN currency cy ON gbl.currency_id = cy.id INNER JOIN company_users cmpu ON gbl.company_user_id = cmpu.id WHERE gbl.company_user_id = company_user_id;

CREATE  PROCEDURE select_for_company_rates(IN company_user_id int)
SELECT ra.id,cont.company_user_id,cont.id as contract_id,cont.name as name, cont.number,cont.validity as validy,cont.expire,cont.status as status, har_orig.display_name as port_orig,har_dest.display_name as port_dest,car.name as carrier,ra.twuenty,ra.forty,ra.fortyhc , ra.fortynor,ra.fortyfive, curr.alphacode as currency from rates ra INNER JOIN harbors har_orig ON har_orig.id = ra.origin_port INNER JOIN harbors har_dest ON har_dest.id = ra.destiny_port INNER JOIN carriers car on car.id = ra.carrier_id INNER JOIN currency curr on curr.id = ra.currency_id INNER JOIN contracts cont on cont.id = ra.contract_id WHERE cont.company_user_id = company_user_id;

CREATE  PROCEDURE select_globalcharge(IN account_id int)
SELECT gb.id, (SELECT GROUP_CONCAT(DISTINCT(har.display_name) SEPARATOR ', ') FROM globalcharport gbp INNER JOIN harbors har on har.id = gbp.port_orig WHERE gbp.globalcharge_id = gb.id ) as port_orig , (SELECT GROUP_CONCAT(DISTINCT(har.display_name) SEPARATOR ', ') FROM globalcharport gbp INNER JOIN harbors har on har.id = gbp.port_dest WHERE gbp.globalcharge_id = gb.id ) as port_dest, (SELECT GROUP_CONCAT(DISTINCT(coun.name) SEPARATOR ', ') FROM globalcharcountry gbCD INNER JOIN countries coun on coun.id = gbCD.country_orig WHERE gbCD.globalcharge_id = gb.id ) as country_orig , (SELECT GROUP_CONCAT(DISTINCT(counD.name) SEPARATOR ', ') FROM globalcharcountry gbCD INNER JOIN countries counD on counD.id = gbCD.country_dest WHERE gbCD.globalcharge_id = gb.id ) as country_dest , (SELECT GROUP_CONCAT(DISTINCT(carr.name) SEPARATOR ', ') FROM globalcharcarrier gbC INNER JOIN carriers carr on carr.id = gbC.carrier_id WHERE gbC.globalcharge_id = gb.id ) as carrier, sg.name as surcharges, td.description as typedestiny, ct.name as calculationtype, gb.ammount, gb.validity,gb.expire, cy.alphacode AS currency, cmpu.name as company_user, gb.account_importation_globalcharge_id FROM globalcharges gb INNER JOIN surcharges sg ON gb.surcharge_id = sg.id INNER JOIN typedestiny td ON gb.typedestiny_id = td.id INNER JOIN calculationtype ct ON gb.calculationtype_id = ct.id INNER JOIN currency cy ON gb.currency_id = cy.id INNER JOIN company_users cmpu ON gb.company_user_id = cmpu.id WHERE gb.account_importation_globalcharge_id = account_id;

CREATE  PROCEDURE select_globalcharge_adm(IN comp_id INT, IN carr_code INT)
SELECT      gc.id AS id,sr.name AS charge,td.description AS charge_type, ctype.name AS calculation_type, (SELECT   GROUP_CONCAT(DISTINCT har.code   SEPARATOR ', ')  FROM (globalcharport gcP JOIN harbors har ON ((har.id = gcP.port_orig))) WHERE (gcP.globalcharge_id = gc.id)) AS origin_port,(SELECT GROUP_CONCAT(DISTINCT har.code SEPARATOR ', ')FROM (globalcharport gcP  JOIN harbors har ON ((har.id = gcP.port_dest))) WHERE(gcP.globalcharge_id = gc.id)) AS destination_port, (SELECT GROUP_CONCAT(DISTINCT coun.name SEPARATOR ', ') FROM (globalcharcountry gcCO JOIN countries coun ON ((coun.id = gcCO.country_orig)))  WHERE (gcCO.globalcharge_id = gc.id)) AS origin_country,(SELECT GROUP_CONCAT(DISTINCT counD.name SEPARATOR ', ') FROM (globalcharcountry gcCD JOIN countries counD ON ((counD.id = gcCD.country_dest))) WHERE (gcCD.globalcharge_id = gc.id)) AS destination_country, (SELECT GROUP_CONCAT(DISTINCT(portPC.name)   SEPARATOR ', ') FROM global_char_port_countries gcPC INNER JOIN harbors portPC on portPC.id = gcPC.port_orig WHERE gcPC.globalcharge_id = gc.id ) as portcountry_orig , (SELECT GROUP_CONCAT(DISTINCT(counPC.name)   SEPARATOR ', ') FROM global_char_port_countries gcPCd INNER JOIN countries counPC on counPC.id = gcPCd.country_dest WHERE gcPCd.globalcharge_id = gc.id ) as portcountry_dest ,(SELECT GROUP_CONCAT(DISTINCT(counCP.name)   SEPARATOR ', ') FROM global_char_country_ports gcCP INNER JOIN countries counCP on counCP.id = gcCP.country_orig WHERE gcCP.globalcharge_id = gc.id ) as countryport_orig , (SELECT GROUP_CONCAT(DISTINCT(counCPd.name)   SEPARATOR ', ') FROM global_char_country_ports gcCPd INNER JOIN harbors counCPd on counCPd.id = gcCPd.port_dest WHERE gcCPd.globalcharge_id = gc.id ) as countryport_dest ,(SELECT GROUP_CONCAT(DISTINCT carr.name SEPARATOR ', ')    FROM(globalcharcarrier gcC JOIN carriers carr ON ((carr.id = gcC.carrier_id)))    WHERE (gcC.globalcharge_id = gc.id)) AS carrier, (SELECT GROUP_CONCAT(DISTINCT carr.uncode SEPARATOR ', ')    FROM(globalcharcarrier gcC JOIN carriers carr ON ((carr.id =  gcC.carrier_id)))   WHERE(gcC.globalcharge_id = gc.id)) AS carriers,gc.ammount AS amount,cur.alphacode AS currency_code,gc.validity AS valid_from,gc.expire AS valid_until,gc.company_user_id AS company_user_id,cmpu.name AS company_user    FROM (((((globalcharges gc JOIN surcharges sr ON ((sr.id = gc.surcharge_id)))JOIN typedestiny td ON ((td.id = gc.typedestiny_id))) JOIN currency cur ON ((cur.id = gc.currency_id))) JOIN calculationtype ctype ON ((ctype.id = gc.calculationtype_id))) JOIN company_users cmpu ON ((cmpu.id = gc.company_user_id)) JOIN globalcharcarrier gcC ON ((gc.id = gcC.globalcharge_id))) where cmpu.id = comp_id AND gcC.carrier_id = carr_code;

CREATE  PROCEDURE select_harbors_search()
SELECT id, display_name, code, harbor_parent from harbors;

CREATE  PROCEDURE select_rates_contract_lcl(IN company_user_id int)
SELECT ra.id,cont.company_user_id,cont.id as contract_id ,cont.name as name , cont.number,cont.validity as validy,cont.expire,cont.status as status, har_orig.display_name as port_orig , har_dest.display_name as port_dest , car.name as carrier , ra.uom,ra.minimum, curr.alphacode as currency from rates_lcl ra INNER JOIN harbors har_orig ON har_orig.id = ra.origin_port INNER JOIN harbors har_dest ON har_dest.id = ra.destiny_port INNER JOIN carriers car on car.id = ra.carrier_id INNER JOIN currency curr on curr.id = ra.currency_id INNER JOIN contracts_lcl cont on cont.id = ra.contractlcl_id WHERE cont.company_user_id = company_user_id;

CREATE  PROCEDURE select_request_fcl(IN date_start VARCHAR(30),IN date_end VARCHAR(30))
SELECT nr.id,cpu.name as company_user,nr.namecontract,nr.numbercontract,nr.data as request_data ,dr.name as direction,nr.namefile,(SELECT GROUP_CONCAT( DISTINCT(cr.name) SEPARATOR ', ')  FROM request_fcl_carriers rcarr INNer JOIN carriers cr ON rcarr.carrier_id=cr.id WHERE nr.id=rcarr.request_id) as carriers, nr.validation,nr.created,CONCAT(us.name,CONCAT(' ',us.lastname)) as user,nr.time_total as time_elapsed,nr.username_load,nr.status,nr.contract_id as contract,cts.validator as validator_contract,nr.erased_contract FROM newcontractrequests nr INNER JOIN company_users cpu ON nr.company_user_id = cpu.id LEFT JOIN directions dr ON  dr.id = nr.direction_id LEFT JOIN contracts cts on nr.contract_id=cts.id INNER JOIN users us ON nr.user_id=us.id WHERE nr.created BETWEEN date_start AND date_end;

CREATE  PROCEDURE select_request_fcl_v2(IN date_start VARCHAR(30),IN date_end VARCHAR(30))
SELECT nr.id,cpu.name as company_user,nr.namecontract,nr.numbercontract,nr.data as request_data ,dr.name as direction,nr.namefile,(SELECT GROUP_CONCAT( DISTINCT(cr.name) SEPARATOR ', ')  FROM request_fcl_carriers rcarr INNer JOIN carriers cr ON rcarr.carrier_id=cr.id WHERE nr.id=rcarr.request_id) as carriers, nr.validation,nr.created,CONCAT(us.name,CONCAT(' ',us.lastname)) as user,nr.time_total as time_elapsed,nr.username_load,nr.status,nr.contract_id as contract,cts.validator as validator_contract,nr.erased_contract FROM newcontractrequests nr INNER JOIN company_users cpu ON nr.company_user_id = cpu.id LEFT JOIN directions dr ON  dr.id = nr.direction_id LEFT JOIN contracts cts on nr.contract_id=cts.id INNER JOIN users us ON nr.user_id=us.id WHERE nr.created BETWEEN date_start AND date_end and nr.status_erased = '0';

CREATE  PROCEDURE select_request_lcl()
SELECT nr.id,cpu.name as company_user,nr.namecontract,dr.name as direction,(SELECT GROUP_CONCAT( DISTINCT(cr.name) SEPARATOR ', ')  FROM request_lcl_carriers rcarr INNER JOIN carriers cr ON rcarr.carrier_id=cr.id WHERE nr.id=rcarr.request_id) as carriers, nr.validation,nr.created,CONCAT(us.name,CONCAT(' ',us.lastname)) as user,nr.time_total as time_elapsed,nr.username_load,nr.status,nr.contract_id as contract FROM new_contract_request_lcl nr INNER JOIN company_users cpu ON nr.company_user_id = cpu.id LEFT JOIN directions dr ON  dr.id = nr.direction_id INNER JOIN users us ON nr.user_id=us.id;

CREATE  PROCEDURE surcharge_list_proc(IN company_user int)
SELECT sr.id,sr.name,sr.description,(CASE WHEN strm.name != '' THEN strm.name ELSE '-------' END) as sale_term,(CASE WHEN cmpu.name != '' THEN cmpu.name ELSE 'General' END) as company_user from surcharges sr LEFT JOIN company_users cmpu ON cmpu.id=sr.company_user_id LEFT JOIN sale_terms strm ON strm.id=sr.sale_term_id WHERE sr.company_user_id IS NULL OR sr.company_user_id=company_user;
